package com.great.caipiao.db.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.great.caipiao.db.entity.MainData;
import com.great.caipiao.db.entity.ConfigData;

import com.great.caipiao.db.greendao.MainDataDao;
import com.great.caipiao.db.greendao.ConfigDataDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mainDataDaoConfig;
    private final DaoConfig configDataDaoConfig;

    private final MainDataDao mainDataDao;
    private final ConfigDataDao configDataDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mainDataDaoConfig = daoConfigMap.get(MainDataDao.class).clone();
        mainDataDaoConfig.initIdentityScope(type);

        configDataDaoConfig = daoConfigMap.get(ConfigDataDao.class).clone();
        configDataDaoConfig.initIdentityScope(type);

        mainDataDao = new MainDataDao(mainDataDaoConfig, this);
        configDataDao = new ConfigDataDao(configDataDaoConfig, this);

        registerDao(MainData.class, mainDataDao);
        registerDao(ConfigData.class, configDataDao);
    }
    
    public void clear() {
        mainDataDaoConfig.clearIdentityScope();
        configDataDaoConfig.clearIdentityScope();
    }

    public MainDataDao getMainDataDao() {
        return mainDataDao;
    }

    public ConfigDataDao getConfigDataDao() {
        return configDataDao;
    }

}
